### ISSUE TITLE
users module should allow smb parameter when password_disabled is defined

### ISSUE THREAD

**Issue by steven-ellis** [arensb/ansible-truenas#12]
Reference
- https://www.truenas.com/docs/scale/scaleclireference/account/cliuser/#create-configuration-properties

smb defaults to true which conflicts with password_disabled. Ideally using password_disabled should require the smb parameter so that so we have to explicitly disable the value.

**Comment by steven-ellis** [comment]
Error is
- user_create.password_disabled: Password authentication may not be disabled for SMB users

**Comment by arensb** [comment]
@steven-ellis Do you have a playbook that illustrates the problem you're seeing?

**Comment by steven-ellis** [comment]
Here is an example

```
   - name: Make sure  mythtv user exists
      arensb.truenas.user:
        name: mythtv
        uid: 1000
        groups: 'users,mythtv'
        password_disabled: yes
```
