### ISSUE TITLE
Can't have the same NFS mount point with different permissions

### ISSUE THREAD

**Issue by steven-ellis** [arensb/ansible-truenas#16]
Example would be to export my MP3 directory ro to media players but rw to my desktop

```
- name: RO export for media players
  arensb.truenas.sharing_nfs:
    - name: MP3 ro export
      path: /mnt/pool0/MP3
      readonly: false
      hosts:
            - 192.168.1.8
            - 192.168.1.9

- name: RW Export for my desktop
  arensb.truenas.sharing_nfs:
    - name: MP3 rw export
      readonly: true
      path: /mnt/pool0/MP3
      hosts:
            - 192.168.1.2

```

Only the second share will be created when you check the GUI on TrueNAS Scale.

Look like you're using "path" as the unique identified when it is possible to have mutiple exports with the same path.
