### ISSUE TITLE
Can't set owner of dataset using 'arensb.truenas.filesystem'

### ISSUE THREAD

**Issue by MozzieBytes** [arensb/ansible-truenas#19]
Due to the current limitations of the filesystem module, you can't set the ownership of a dataset to any non-root user. 

This limitation means that if you want any NFS user to interact with the share as if they own it, you need to set 'mapall_user' to root on the NFS share.  This has downsides in that we don't always want users of our nfs shares to be masquerading as root.

I've achieved this in the short term by using `ansible.builtin.file` post-step, but it would be best to do this when the filesystem is created:
```yaml
      ansible.builtin.file:
        path: /mnt/pool0/dataset
        state: directory
        recurse: yes
        owner: myuser
        group: mygroup
```

I  can try and look into this myself when I have spare time, but my python skills are rusty.
